name: cabme
description: A new Flutter project.

publish_to: "none"

version: 2.1.0+12

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  bottom_picker: ^4.1.1
  cached_network_image: ^3.4.1
  clipboard: ^3.0.14
  cloud_firestore: ^6.0.2
  crypto: ^3.0.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  device_preview: ^1.3.1
  dio: any
  dotted_border: ^3.1.0
  file_picker: ^10.3.10
  firebase_app_check: ^0.4.1
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_database: ^12.0.2
  firebase_messaging: ^16.0.2
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_google_places_hoc081098: ^2.0.0
  flutter_html: any
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^20.1.0
  flutter_localizations:
    sdk: flutter
  flutter_osm_plugin: ^1.3.6
  flutter_paypal_native: ^2.1.0
  flutter_polyline_points: ^3.1.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.0.10+1
  flutter_upayments: ^1.0.2
  geocoding: ^4.0.0
  geolocator: any
  get: 4.6.6
  google_api_headers: any
  google_fonts: ^8.0.1
  google_maps_flutter: ^2.9.0
  google_maps_place_picker_mb: ^3.1.2
  google_sign_in: ^7.2.0
  googleapis_auth: ^2.0.0
  http: any
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  in_app_review: ^2.0.9
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  location: ^8.0.1
  map_launcher: ^4.4.2
  omni_datetime_picker: ^2.0.2
  package_info_plus: any
  path_provider: ^2.1.4
  pdf: ^3.11.3
  photo_view: ^0.15.0
  pinput: ^6.0.2
  printing: ^5.14.2
  provider: ^6.1.2
  share_plus: ^12.0.0
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^7.0.1
  syncfusion_flutter_pdfviewer: any
  text_scroll: ^0.2.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  video_compress: ^3.1.3
  video_player: ^2.9.2
  video_thumbnail: ^0.5.3
  webview_flutter: any

dependency_overrides:
  geolocator: ^14.0.2
  google_api_headers: ^5.1.0
  http: ^1.2.2
  package_info_plus: ^8.3.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.23.6

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/
